twit_clone/config/routes.rb
Rails.application.routes.draw do
  resources :towits do
   collection do
   post :confirm
  #get 'towits/index'
  #get 'towits/new'
  #get 'towits/edit'
  #get 'towits/create'
  #get '/towits', to: 'towits#index'
  #post '/towits', to: 'towits#create'
  #post '/towits', to: 'towits#edit'
  #post '/towits', to: 'towits#new'
end
end
end

  #resources :blogs do
   #collection do
   #end
    # post :confirm
 #get 'blogs/index'
 #get 'blogs/new'
 #get 'blogs/edit'
 #get 'blogs/create'
 #get '/blogs', to: 'blogs#index'
 #post '/blogs', to: 'blogs#create'
 #post '/blogs', to: 'blogs#edit'
 #post '/blogs', to: 'blogs#new'

twit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

twit_clone/app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
end

twit_clone/app/models/model.rb
class Model < ApplicationRecord
end

twit_clone/app/models/towit.rb
class Towit < ApplicationRecord
validates :messages, presence: true
validates :messages, length: { in: 1..140 }
end

twit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

twit_clone/app/controllers/towits_controller.rb
class TowitsController < ApplicationController
  before_action :set_towit, only: [:show, :edit, :update, :destroy]
   def index
     @towits = Towit.all
   end

   def new
     @towit = Towit.new
   end

   def create
    @towit = Towit.new(towit_params)
     if params[:back]
     render:new
    else
      if @towit.save
    redirect_to towits_path, notice: "I have make twit!"
    else
    render:new
  end
  end
  end 
  def show
  end

  def edit
  end

  def update
      if @towit.update(towit_params)
        redirect_to towits_path, notice: "twit edited!"
      else
        render :edit
      end
  end

  def destroy
    @towit.destroy
    redirect_to towits_path, notice:"twit deleted!"
  end
  def ​confirm
      ​@towit = Towit.new(towit_params)
      render :new if @towit.invalid?
end
  private
  def set_towit
    @towit = Towit.find(params[:id])
  end
  def towit_params
    params.require(:towit).permit(:messages, :content)
  end
  end

twit_clone/app/helpers/towits_helper.rb
module TowitsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_towits_path
    elsif action_name == 'edit'
      towit_path
    end
  end
end

twit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

twit_clone/app/views/towits/_form.html.erb
<%= form_with(model: @towit, local: true) do |form| %>
  <% if @towit.errors.any? %>
    <div id="error_explanation">
      <h2><%= @towit.errors.count %>There are errors.</h2>
      <ul>
      <% @towit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="towit_messages">
    <%= form.label :messages %>
    <%= form.text_field :messages %>
    </div>
    <div class="towit_messages">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "twit list return to screen", towits_path %>

twit_clone/app/views/towits/confirm.html.erb
<body class= "body">
<%= stylesheet_link_tag "towits" %>
<h3>Send with the following Content</​h3>
  <%= form_with(model: @towit, url: towits_path, local: true) do |form| %>
  <%= form.hidden_field :messages %>
  <%= form.hidden_field :content %>
  <p> messages:<%= @towit.messages %><​/p>
  <p> Text:<%=​ @towit.content %></p>
  <%= form.submit "to register" %>
  <%= form.submit "Return", name: 'back' %>
<% end %>

</body>

twit_clone/app/views/towits/edit.html.erb
<body class= "body">
<%= stylesheet_link_tag "towits" %>
<h2>Edit towit</h2>
<%= render 'form' %>
</body>

twit_clone/app/views/towits/index.html.erb
<body class= "body">
<p><%= notice %></p>
  <%= stylesheet_link_tag "towits" %>
  <%= stylesheet_link_tag "normalize" %>
  <header class= "header">

      <p class= "logo"><%= image_tag("logoo.png") %> </p>


  </header>
    <table>
    <tr>
      <th>Messages</th>
      <th>Content</th>
    </tr>
        <% @towits.each do |towit| %>
    <tr>
      <td><%= towit.messages %></td>
      <td><%= towit.content %></td>
      <td><%= link_to 'Check new towit', towit_path(towit.id) %></td>
      <td><%= link_to "Edit towit", edit_towit_path(towit.id), data: { confirm: 'Can I really edit it?' } %></td>
      <td><%= link_to 'Delete towit', towit_path(towit.id), method: :delete ,data: { confirm: 'Can i really delete it？' } %></td>
    </tr>
    <% end %>
    <br>
     <td  width="20%" valign="left" bgcolor="pink"> <%= link_to 'Post a new towit', new_towit_path  %> </td>
     </table>
<footer>
  <p class="left">© 2020 Copyright</p>
  <ul>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   <li a href="#" class="fa fa-facebook"></li></a>
   <li a href="#" class="fa fa-twitter"></li></a>
   <li a href="#" class="fa fa-youtube"></li></a>
   <li a href="#" class="fa fa-linkedin"></li></a>
  </ul>
</footer>
</body>

twit_clone/app/views/towits/new.html.erb
<body class= "body">
  <%= stylesheet_link_tag "towits" %>
<h2>Create new towait</h2>
<%= render 'form' %>
</body>

twit_clone/app/views/towits/show.html.erb
<body class= "body">
<%= stylesheet_link_tag "towits" %>
<h1>Blog details screen</h1>
<p>title: <%= @towit.messages %></p>
<p>Content: <%= @towit.content %></p>
</body>